Добавить классы и контроллеры для User и Films
missfury/java-filmorate pull request #7
Opened 2023-05-02 09:40 UTC by missfury

2023-05-03 03:21 UTC, EvgenyKoptubenko commented
Если есть желание, сделай так, чтобы в ответе писалось что конкретно передано неправильно
curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"FilmName",
	"email":"email@email.com",
  "login":"login",
	"birthday":"2001-01-01",
	"duration":22
}'

{
	"timestamp": "2023-05-03T03:21:17.941+00:00",
	"status": 400,
	"error": "Bad Request",
	"path": "/films"
}

2023-05-03 03:24 UTC, EvgenyKoptubenko commented
Почему-то нельзя вытащить одного пользователя
curl --request GET \
  --url http://localhost:8080/users/1 \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"nameItem",
	"email":"email3@email.com"
}'

2023-05-03 03:25 UTC, EvgenyKoptubenko commented
Запрос приводит к 500-й ошибке, хотя должен быть bad Request
curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"FilmName",
	"description":"descriptionItem",
	"duration": 22,
	"releaseDate": "1012-04-23T18:25:43.511Z"
}'

{
	"timestamp": "2023-05-03T03:25:18.984+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films"
}

2023-05-03 03:26 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть несколько предложений по улучшению

2023-05-05 22:45 UTC, missfury commented
> 

Совсем на этом застряла и безуспешно. Так что сдаюсь

2023-05-06 00:12 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-05-06 17:22 UTC, merged