feat: Реализована база данных и сохранение в нее информации
missfury/java-filmorate pull request #9
Opened 2023-06-08 21:47 UTC by missfury

2023-06-10 00:10 UTC, NikolaiDem requested changes

2023-06-10 00:10 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public void addFriendship(int userId, int friendId) {
Для дружбы между 1-ым и 2-ым юзерами планировалось все же создавать одну запись в БД или 2? Если 2, то зачем нужен statsu?

2023-06-10 00:10 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        Set<Integer> friends = new HashSet<>(getFriendsIdByUserId(id));
Здесь возникает проблема N+1 запроса как и с фильмами ) Друзей нужно получать для всего списка юзеров одним запросом

2023-06-10 00:10 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +                                     id              INTEGER         PRIMARY KEY AUTO_INCREMENT,
Выровнять отступы и далее тоже

2023-06-11 05:21 UTC, missfury commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@NoArgsConstructor
Для того, что мне в тестах нужен конструктор без параметров, чтобы объявить новый экземпляр класса, а потом установить тестовые значения полей. А Data сгенерирует RequiredArgsConstructor, который как раз включает final или NonNull поля, которых у меня нет. Да и не нужен он мне, т.к. используются или все аргументы сразу или никаких. Конструктор без аргументов наоборот при наличии финальных полей не сгенерируется, потому что они требуют инициализации. Убирать аннотацию, чтобы прописывать конструктор, который все же нужен - ну, как-то странно.

2023-06-11 05:23 UTC, missfury commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@NoArgsConstructor
Аналогично с фильмом - не лишний, а запасной)

2023-06-11 06:10 UTC, missfury commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(filmId).getUsersLikes().contains(userId))
Насчет отдельного метода согласна, но я хотела бы его реализовать в сервисе. Модель - это все же описание структуры таблицы, и логика работы там совсем ни к чему. В итоге все равно получится один метод, где придется менять код в случае чего.

2023-06-11 06:15 UTC, missfury commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!userStorage.getUserById(userId).getFriends().contains(friendId))
Аналогично фильму

2023-06-11 09:41 UTC, missfury commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public void addFriendship(int userId, int friendId) {
Одна запись

2023-06-11 14:53 UTC, missfury commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private Film makeFilm(ResultSet resultSet, int rowNum) throws SQLException {
Метод вызывается только для getFilmById

2023-06-11 16:08 UTC, missfury commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        for (Genre genre : film.getGenres()) {
Я не разобралась, как этим пользоваться и удалила опцию, т.к. она не обязательная, а дедлайн уже завтра. Но буду благодарна за ссылку, где можно почитать адекватное объяснение.

2023-06-11 19:41 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@NoArgsConstructor
Ой, я же его вроде удалял этот коммент )

2023-06-11 19:53 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilmById(filmId).getUsersLikes().contains(userId))
Верно, бизнес логику лучше помещать в доменные объекты (если подход объектно-ориентированный), которые выделены в отдельный слой как dto и data объекты (модель).
А такого слоя нет, подход у нас в виде паттерна Transaction Script, который предлагает поместить всю логику в сервис, а объекты сделать максимально "dummy" только с геттерами и сеттерами. Тогда валидно вынести в отдельный метод сервиса, да

2023-06-11 20:00 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        for (Genre genre : film.getGenres()) {
https://www.baeldung.com/spring-jdbc-batch-inserts
Еще есть интересная книга "High-Performance Java Persistence"

2023-06-11 20:07 UTC, missfury commented
Я уже не могу (( Правила, правила - тесты не проходят. С 7 утра сижу, а толку чуть. Уже не понимаю, что исправила, а что нет - глаза в кучу. Так что, очень извиняюсь и сдаю как есть ((

2023-06-12 13:00 UTC, NikolaiDem requested changes

2023-06-12 13:00 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public void addFriendship(int userId, int friendId) {
А создается 2 записи

2023-06-13 22:04 UTC, NikolaiDem requested changes

2023-06-13 22:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                "LEFT OUTER JOIN users AS u ON u.id = f.friend_id " +
Для чего здесь джойн к users? Ведь в выборке только friend_id

2023-06-13 22:04 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        if (getUserById(userId) == null || userId < 0) {
getUserById(userId).isEmpty()
А проверки на неотрицательность лучше вынести в контроллер через @Positive

2023-06-14 01:44 UTC, missfury commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                "GROUP BY films.id, films.name, films.description, films.release_date, films.duration " +
А можно не надо? Так до бесконечности можно переписывать все, т.к. идеального не существует.

2023-06-14 01:47 UTC, missfury commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        if (getUserById(userId) == null || userId < 0) {
Не проходит тесты постмана в этом случае. Опытным путем выяснилось, что если убрать аннотацию и добавить проверку, тогда проходит. А с аннотацией и проверкой нет.

2023-06-14 16:44 UTC, missfury commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return jdbcTemplate.query(sqlQuery, this::makeFilm,limitSize);
Ничего у меня не получилось, только ошибки в постмане. Спрашивала у нескольких знакомых помощи, они тоже не знают, что не удивительно - в теории и близко такого не было. В общем, я пас. 15 часов страданий впустую.
Приятно было познакомиться. Спасибо за перспективу отчисления с курса и нервный срыв.

2023-06-16 05:50 UTC, NikolaiDem approved these changes

2023-06-16 07:21 UTC, merged